In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data/Henry_cardiac_MRI2.csv')

In [3]:
df

,LVEDV,LVESV,LVM_diastole,LVM_indexed,LVEDV_indexed,LVESV_indexed,LVSV,LVSV_indexed,RVM,RVM_indexed,Gender,Outcome
0,145.901893,50.747271,118.433677,63.342075,72.107002,19.909333,99.587306,51.648048,31.527847,13.039273,1,1
1,149.966563,60.917703,126.866576,59.314103,72.880787,26.257485,92.259578,50.054726,32.480505,13.810737,0,1
2,140.777720,45.493367,114.551498,59.344897,72.345370,27.161417,100.664456,44.157988,29.785900,16.056156,1,1
3,158.153330,55.135643,111.449275,54.078818,80.981210,23.801519,88.966952,47.616209,31.074244,13.562996,1,1
4,141.632134,69.970111,118.189333,52.552210,83.231637,28.778969,86.972592,40.486547,32.369627,12.918013,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
76,153.160296,65.139081,98.829441,60.460654,70.888906,26.807626,101.417476,53.878989,38.593801,15.669456,1,0
77,145.037944,69.465546,113.605692,62.190196,85.447398,32.610479,90.680893,44.711930,26.641066,18.092570,1,0
78,129.428705,52.443500,95.344378,55.330893,84.884727,25.928861,102.664220,45.122405,30.815330,19.081699,0,0
79,160.436681,53.856854,123.947428,55.293546,73.166533,26.733940,91.685793,51.162284,40.778029,14.427789,1,0
80,143.667708,53.518593,119.396562,53.211076,73.977903,30.769007,107.473057,43.494838,29.053569,14.381710,1,0

In [4]:
### Independent and Dependent features
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [5]:
X.head()

,LVEDV,LVESV,LVM_diastole,LVM_indexed,LVEDV_indexed,LVESV_indexed,LVSV,LVSV_indexed,RVM,RVM_indexed,Gender
0,145.901893,50.747271,118.433677,63.342075,72.107002,19.909333,99.587306,51.648048,31.527847,13.039273,1
1,149.966563,60.917703,126.866576,59.314103,72.880787,26.257485,92.259578,50.054726,32.480505,13.810737,0
2,140.777720,45.493367,114.551498,59.344897,72.345370,27.161417,100.664456,44.157988,29.785900,16.056156,1
3,158.153330,55.135643,111.449275,54.078818,80.981210,23.801519,88.966952,47.616209,31.074244,13.562996,1
4,141.632134,69.970111,118.189333,52.552210,83.231637,28.778969,86.972592,40.486547,32.369627,12.918013,0

In [6]:
y.head(20)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: Outcome, dtype: int64

In [7]:
### Train Test Split
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [9]:
### Implement Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [10]:
## Prediction
y_pred=classifier.predict(X_test)

In [11]:
### Check Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

In [12]:
score

0.84

In [13]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("Cclassifier.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

In [14]:
import numpy as np

In [ ]:
classifier.predict([[149.966563,60.91770268,126.866576,59.31410308,72.88078726,26.25748473,92.2595776,50.05472599,32.48050475,13.8107365,1
]])